name: Deploy WordPress on WSL

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Deploy with Docker Compose
        run: |
          docker compose down || true
          docker rm -f wordpress_db wordpress_app || true
          docker compose up -d --build

      - name: Check Container Status
        run: |
          docker compose ps
